apiVersion: v1
kind: Service
metadata:
  name: zzz
  labels:
    app: zzz
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    nodePort: 30082
    targetPort: 8080
  selector:
    app: zzz
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zzz-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: zzz
        version: v1
    spec:
      containers:
      - name: zzz
        image: neighbor/zzz:latest
        imagePullPolicy: IfNotPresent
      imagePullSecrets:
      - name: neighborsecret
